import requests
import base64
import json


def run_server(handle_data,
               initialize,
               before_trading_start,
               analyze,
               algofile,
               algotext,
               defines,
               data_frequency,
               capital_base,
               data,
               bundle,
               bundle_timestamp,
               start,
               end,
               output,
               print_algo,
               local_namespace,
               environ,
               live,
               exchange,
               algo_namespace,
               base_currency,
               live_graph,
               analyze_live,
               simulate_orders,
               auth_aliases,
               stats_output):

    json_file = {'arguments': {
        'handle_data': handle_data,
        'initialize': initialize,
        'before_trading_start': before_trading_start,
        'analyze': analyze,
        'algofile': base64.b64encode(algofile.read()),
        'algotext': algotext,
        'defines': defines,
        'data_frequency': data_frequency,
        'capital_base': capital_base,
        'data': data,
        'bundle': bundle,
        'bundle_timestamp': bundle_timestamp,
        'start': start,
        'end': end,
        'output': output,
        'print_algo': print_algo,
        'local_namespace': local_namespace,
        'environ': None,
        'live': False,
        'exchange': exchange,
        'algo_namespace': algo_namespace,
        'base_currency': base_currency,
        'live_graph': live_graph,
        'analyze_live': analyze_live,
        'simulate_orders': simulate_orders,
        'auth_aliases': auth_aliases,
        'stats_output': stats_output,
    }}

    url = 'http://127.0.0.1:5000/todo/api/v1.0/tasks'
    response = requests.post(url, json=json_file)
